services:
  switch:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: jpos-q2-switch:latest
    container_name: jpos-q2-switch
    environment:
      BASE_DERIVATION_KEY: 0123456789ABCDEFFEDCBA9876543210
      JAVA_OPTS: -Dswitch.listener.debug=true
    ports:
      - "9000:9000"
    volumes:
      - ./cfg:/app/cfg:ro
      - ./deploy:/app/deploy:ro
      - ~/.m2:/root/.m2
    restart: unless-stopped
